x <- rnorm(100)
hist(x)
y <- rnorm(100)
plot(x, y)
z <- rnorm(100)
plot(x, z)
par(mar = c(2, 2, 2, 2))
plot(x, y)
par(mar = c(4, 4, 2, 2))
plot(x, y)
plot(x, y, pch = 20)
plot(x, y, pch = 19)
plot(x, y, pch = 3)
plot(x, y, pch = 2)
plot(x, y, pch = 4)
example(points)
plot(x, y, pch = 20)
title("Scatterplot")
text(-2, -2, "Label")
legend("topleft", "Data", pch = 20)
fit <- lm(y ~ x)
abline(fit)
abline(fit, lwd = 3)
abline(fit, lwd = 3, col = "blue")
plot(x, y, xlab = "Weight", ylab = "Height", main = "Scatterplot", pch = 20)
legend("topright", legend = "Data", pch = 20)
fit <- lm(y ~ x)
abline(fit, lwd = 3, col = "red")
z <- rpois(100, 2)
par(mfrow = c(2,1))
# Mfrow and Mfcol defines the layout of the canvas
# number of rows and columns
plot(x, y, pch = 20)
plot(x, z, pch = 19)
# Points
x <- rnorm(100)
y <- x + rnorm(100)
g <- gl(2, 50, labels = c("Males", "Females"))
str(g)
plot(x, y)
plot(x, y, type = "n")
points(x[g == "Males"], y[g == "Males"], col = "green")
points(x[g == "Females"], y[g == "Females"], col = "blue")
points(x[g == "Females"], y[g == "Females"], col = "blue", pch = 19)